# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonFinalResIds=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=35
org.gradle.java.home=/home/roshan/Downloads/android-studio-quail1-patch2-linux/android-studio/jbr

